export const SET_TO_DO_LIST_REQUEST:string = "SET_TO_DO_LIST_REQUEST"
export const SET_TO_DO_LIST_SUCCESS:string = "SET_TO_DO_LIST_SUCCESS"
export const SET_TO_DO_LIST_ERROR:string = "SET_TO_DO_LIST_ERROR"
export const GET_TO_DO_LIST_REQUEST:string = "GET_TO_DO_LIST_REQUEST"
